# version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
       - db
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

  
networks:
  app-network:
    driver: bridge
volumes:
  pgdata: